MegaCable.Web/Controllers/ContratoController.cs
using MegaCable.Entities;
using MegaCable.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MegaCable.Web.Controllers
{
    public class ContratoController : Controller
    {
        private IContratoService contratoService;
        private IPlanService planService;
        private ISectorService sectorService;

        public ContratoController(IContratoService contratoService, 
            IPlanService planService, ISectorService sectorService)
        {
            this.contratoService = contratoService;
            this.planService = planService;
            this.sectorService = sectorService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var contrato = contratoService.GetContrato();
            return View(contrato);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var plan = planService.GetPlanes();
            ViewBag.Plan = new SelectList(plan, "Id", "NombrePlan");
            var sector = sectorService.GetSectores();
            ViewBag.Sector = new SelectList(sector, "Id", "NombreSector");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Contrato contrato)
        {
            if (ModelState.IsValid)
            {
                contratoService.Guardar(contrato);
                return RedirectToAction("Index");
            }
            var plan = planService.GetPlanes();
            ViewBag.Plan = new SelectList(plan, "Id", "NombrePlan");
            var sector = sectorService.GetSectores();
            ViewBag.Sector = new SelectList(sector, "Id", "NombreSector");
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id=0)
        {
            var plan = planService.GetPlanes();
            ViewBag.Plan = new SelectList(plan, "Id", "NombrePlan");
            var sector = sectorService.GetSectores();
            ViewBag.Sector = new SelectList(sector, "Id", "NombreSector");
            var contrato = contratoService.GetContrato(id);
            return View(contrato);
        }

        [HttpPost]
        public ActionResult Edit(Contrato contrato)
        {
            if (ModelState.IsValid)
            {
                contratoService.Editar(contrato);
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

MegaCable.Web/Views/Contrato/Create.cshtml
@model MegaCable.Entities.Contrato

@{
    ViewBag.Title = "Nuevo";
}

<div align="center">
    <h3>Sistema de Servicios MEGACABLENET</h3>
</div>

@using (Html.BeginForm("Create", "Contrato", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Nuevo Contrato</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Label("Ciudad: CAJAMARCA")
        <hr />
        <h4>Datos del Solicitante</h4>
        <div class="form-group">
            <p></p>
            &emsp;
            @Html.Label("Apellido Paterno:")
            @Html.EditorFor(model => model.Abonado.ApPaterno)
            @Html.ValidationMessageFor(model => model.Abonado.ApPaterno, "", new { @class = "text-danger" })
            &emsp;
            @Html.Label("Apellido Materno:")
            @Html.EditorFor(model => model.Abonado.ApMaterno)
            @Html.ValidationMessageFor(model => model.Abonado.ApMaterno, "", new { @class = "text-danger" })
            &emsp;
            @Html.Label("Nombres:")
            @Html.EditorFor(model => model.Abonado.Nombres)
            @Html.ValidationMessageFor(model => model.Abonado.Nombres, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            &emsp;
            @Html.Label("DNI:")
            @Html.EditorFor(model => model.Abonado.DNI)
            @Html.ValidationMessageFor(model => model.Abonado.DNI, "", new { @class = "text-danger" })
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            @Html.Label("Email:")
            @Html.EditorFor(model => model.Abonado.Email)
            @Html.ValidationMessageFor(model => model.Abonado.Email, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            &emsp;&emsp;&emsp;
            &emsp;&emsp;
            @Html.Label("Telefono:")
            @Html.EditorFor(model => model.Abonado.Telefono)
            @Html.ValidationMessageFor(model => model.Abonado.Telefono, "", new { @class = "text-danger" })
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&ensp;
            @Html.Label("Celular:")
            @Html.EditorFor(model => model.Abonado.Celular)
            @Html.ValidationMessageFor(model => model.Abonado.Celular, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            &emsp;&emsp;&emsp;
            &emsp;&ensp;
            @Html.Label("Direccion:")
            @Html.EditorFor(model => model.Abonado.Direccion)
            @Html.ValidationMessageFor(model => model.Abonado.Direccion, "", new { @class = "text-danger" })
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            @Html.Label("Sector:")
            @Html.DropDownList("SectorId", ViewBag.Sector as SelectList, "Seleccione Sector")
            @Html.ValidationMessageFor(model => model.Sector.Id, "", new { @class = "text-danger" })
        </div>
        <hr />
        <h4>Requisitos</h4>
        <div class="form-group">
            @Html.Label("Copia de DNI:", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CopiaDNI)
                    @Html.ValidationMessageFor(model => model.CopiaDNI, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Recibo Luz/Agua:", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ReciboLuzAgua)
                    @Html.ValidationMessageFor(model => model.ReciboLuzAgua, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Observaciones:", new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Observaciones)
            @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
        </div>
        <hr />
        <h4>Producto</h4>
        <div class="form-group">
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            &emsp;
            @Html.Label("Plan:")
            @Html.DropDownList("PlanId", ViewBag.Plan as SelectList, "Seleccione Plan")
            @Html.ValidationMessageFor(model => model.Plan.Id, "", new { @class = "text-danger" })
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            @Html.Label("Velocidad Plan:")
            <p></p>
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            &emsp;
            @Html.Label("Valor Plan:")
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            @Html.Label("Instalacion:")
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            @Html.Label("Pago Total:")
        </div>
        <hr />
        <h4>Facturacion</h4>
        <div class="form-group">
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            &emsp;
            @Html.Label("Dia:")
            @Html.EditorFor(model => model.FechaPago)
            @Html.ValidationMessageFor(model => model.FechaPago, "", new { @class = "text-danger" })
        </div>
        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MegaCable.Web/Views/Contrato/Edit.cshtml
@model MegaCable.Entities.Contrato

@{
    ViewBag.Title = "Editar";
}

<h3>Editar Contratos</h3>

@using (Html.BeginForm("Edit", "Contrato", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        @Html.Label("Ciudad: CAJAMARCA")
        <hr />
        <h4>Datos del Solicitante</h4>
        <div class="form-group">
            <p></p>
            &emsp;
            @Html.Label("Apellido Paterno:")
            @Html.EditorFor(model => model.Abonado.ApPaterno)
            @Html.ValidationMessageFor(model => model.Abonado.ApPaterno, "", new { @class = "text-danger" })
            &emsp;
            @Html.Label("Apellido Materno:")
            @Html.EditorFor(model => model.Abonado.ApMaterno)
            @Html.ValidationMessageFor(model => model.Abonado.ApMaterno, "", new { @class = "text-danger" })
            &emsp;
            @Html.Label("Nombres:")
            @Html.EditorFor(model => model.Abonado.Nombres)
            @Html.ValidationMessageFor(model => model.Abonado.Nombres, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            &emsp;
            @Html.Label("DNI:")
            @Html.EditorFor(model => model.Abonado.DNI)
            @Html.ValidationMessageFor(model => model.Abonado.DNI, "", new { @class = "text-danger" })
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;|
            @Html.Label("Email:")
            @Html.EditorFor(model => model.Abonado.Email)
            @Html.ValidationMessageFor(model => model.Abonado.Email, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            &emsp;&emsp;&emsp;
            &emsp;&emsp;
            @Html.Label("Telefono:")
            @Html.EditorFor(model => model.Abonado.Telefono)
            @Html.ValidationMessageFor(model => model.Abonado.Telefono, "", new { @class = "text-danger" })
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&ensp;
            @Html.Label("Celular:")
            @Html.EditorFor(model => model.Abonado.Celular)
            @Html.ValidationMessageFor(model => model.Abonado.Celular, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            &emsp;&emsp;&emsp;
            &emsp;&ensp;
            @Html.Label("Direccion:")
            @Html.EditorFor(model => model.Abonado.Direccion)
            @Html.ValidationMessageFor(model => model.Abonado.Direccion, "", new { @class = "text-danger" })
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            @Html.Label("Sector:")
            @Html.DropDownList("SectorId", ViewBag.Sector as SelectList, "Seleccione Sector")
            @Html.ValidationMessageFor(model => model.Sector.Id, "", new { @class = "text-danger" })
        </div>
        <hr />
        <h4>Requisitos</h4>
        <div class="form-group">
            @Html.Label("Copia de DNI:", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CopiaDNI)
                    @Html.ValidationMessageFor(model => model.CopiaDNI, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Recibo Luz/Agua:", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ReciboLuzAgua)
                    @Html.ValidationMessageFor(model => model.ReciboLuzAgua, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Observaciones:", new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Observaciones)
            @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
        </div>
        <hr />
        <h4>Producto</h4>
        <div class="form-group">
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            &emsp;
            @Html.Label("Plan:")
            @Html.DropDownList("PlanId", ViewBag.Plan as SelectList, "Seleccione Plan")
            @Html.ValidationMessageFor(model => model.Plan.Id, "", new { @class = "text-danger" })
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            @Html.Label("Velocidad Plan:")
            <p></p>
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            &emsp;
            @Html.Label("Valor Plan:")
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            @Html.Label("Instalacion:")
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            @Html.Label("Pago Total:")
        </div>
        <hr />
        <h4>Facturacion</h4>
        <div class="form-group">
            &emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;
            &emsp;
            @Html.Label("Dia:")
            @Html.EditorFor(model => model.FechaPago)
            @Html.ValidationMessageFor(model => model.FechaPago, "", new { @class = "text-danger" })
        </div>
        <hr />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MegaCable.Web/Views/Contrato/Index.cshtml
@model IEnumerable<MegaCable.Entities.Contrato>

@{
    ViewBag.Title = "Contratos";
}

<h3>Lista Contratos</h3>

<p>
    @Html.ActionLink("Crear Nuevo", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.Label("DNI")
        </th>
        <th>
            @Html.Label("Abonado")
        </th>
        <th>
            @Html.Label("Celular")
        </th>
        <th>
            @Html.Label("Sector")
        </th>
        <th>
            @Html.Label("Plan")
        </th>
        <th>
            @Html.Label("Cuota Mensual")
        </th>
        <th>
            @Html.Label("Fecha Pago")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Abonado.DNI)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Abonado.Nombres)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Abonado.Celular)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sector.NombreSector)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Plan.NombrePlan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Plan.ValorPlan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaPago)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id })
        </td>
    </tr>
}

</table>